# Time Series Acquire Exercises
Create a new local git repository and remote repository on github named time-series-exercises. Save this work for this module in your time-series-exercises repo.

The end result of this exercise should be a file named acquire.py.

# ACQUIRE.PY

In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

import os
import datetime
import requests

## STARWARS PEOPLE

### 1. Using the code from the lesson as a guide and the REST API from https://swapi.dev/ as we did in the lesson, create a dataframe named people that has all of the data for people.

In [2]:
#Worked to integrated the code steps for one clean code will use this version for acquire.py 
def get_people_data():
    # Initialize the URL for the first page
    data = []
    url = 'https://swapi.dev/api/people/'  
    
    while True:
        # Send a GET request to the SWAPI
        response = requests.get(url)  
        if response.status_code == 200:
            json_data = response.json()
            results = json_data['results']
            data.extend(results)
            # Update the URL with the next page URL
            url = json_data['next']  

            if url is None:
                break
        else:
            print(f"Error: {response.status_code}")
            break
    # Create a DataFrame using the collected data
    df = pd.DataFrame(data)  
    return df

In [3]:
people_df = get_people_data()

In [4]:
people_df.shape

(82, 16)

In [5]:
people_df.head().T

,0,1,2,3,4
name,Luke Skywalker,C-3PO,R2-D2,Darth Vader,Leia Organa
height,172,167,96,202,150
mass,77,75,32,136,49
hair_color,blond,n/a,n/a,none,brown
skin_color,fair,gold,"white, blue",white,light
eye_color,blue,yellow,red,yellow,brown
birth_year,19BBY,112BBY,33BBY,41.9BBY,19BBY
gender,male,n/a,n/a,male,female
homeworld,https://swapi.dev/api/planets/1/,https://swapi.dev/api/planets/1/,https://swapi.dev/api/planets/8/,https://swapi.dev/api/planets/1/,https://swapi.dev/api/planets/2/
films,"[https://swapi.dev/api/films/1/, https://swapi...","[https://swapi.dev/api/films/1/, https://swapi...","[https://swapi.dev/api/films/1/, https://swapi...","[https://swapi.dev/api/films/1/, https://swapi...","[https://swapi.dev/api/films/1/, https://swapi..."
species,[],[https://swapi.dev/api/species/2/],[https://swapi.dev/api/species/2/],[],[]
vehicles,"[https://swapi.dev/api/vehicles/14/, https://s...",[],[],[],[https://swapi.dev/api/vehicles/30/]
starships,"[https://swapi.dev/api/starships/12/, https://...",[],[],[https://swapi.dev/api/starships/13/],[]
created,2014-12-09T13:50:51.644000Z,2014-12-10T15:10:51.357000Z,2014-12-10T15:11:50.376000Z,2014-12-10T15:18:20.704000Z,2014-12-10T15:20:09.791000Z
edited,2014-12-20T21:17:56.891000Z,2014-12-20T21:17:50.309000Z,2014-12-20T21:17:50.311000Z,2014-12-20T21:17:50.313000Z,2014-12-20T21:17:50.315000Z
url,https://swapi.dev/api/people/1/,https://swapi.dev/api/people/2/,https://swapi.dev/api/people/3/,https://swapi.dev/api/people/4/,https://swapi.dev/api/people/5/

In [6]:
people_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82 entries, 0 to 81
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        82 non-null     object
 1   height      82 non-null     object
 2   mass        82 non-null     object
 3   hair_color  82 non-null     object
 4   skin_color  82 non-null     object
 5   eye_color   82 non-null     object
 6   birth_year  82 non-null     object
 7   gender      82 non-null     object
 8   homeworld   82 non-null     object
 9   films       82 non-null     object
 10  species     82 non-null     object
 11  vehicles    82 non-null     object
 12  starships   82 non-null     object
 13  created     82 non-null     object
 14  edited      82 non-null     object
 15  url         82 non-null     object
dtypes: object(16)
memory usage: 10.4+ KB

# STARWARS PLANETS

### 2. Do the same thing, but for planets.

In [7]:
def get_planets_data():
    # Initialize the URL for the first page
    data = []
    url = 'https://swapi.dev/api/planets/'  
    
    while True:
        # Send a GET request to the SWAPI
        response = requests.get(url)  
        if response.status_code == 200:
            json_data = response.json()
            results = json_data['results']
            data.extend(results)
            url = json_data['next']  

            if url is None:
                break
        else:
            print(f"Error: {response.status_code}")
            break
    # Create a DataFrame using the collected data
    df = pd.DataFrame(data)  
    return df

In [8]:
planets_df = get_planets_data()

In [9]:
planets_df.shape

(60, 14)

In [10]:
planets_df.head().T

,0,1,2,3,4
name,Tatooine,Alderaan,Yavin IV,Hoth,Dagobah
rotation_period,23,24,24,23,23
orbital_period,304,364,4818,549,341
diameter,10465,12500,10200,7200,8900
climate,arid,temperate,"temperate, tropical",frozen,murky
gravity,1 standard,1 standard,1 standard,1.1 standard,N/A
terrain,desert,"grasslands, mountains","jungle, rainforests","tundra, ice caves, mountain ranges","swamp, jungles"
surface_water,1,40,8,100,8
population,200000,2000000000,1000,unknown,unknown
residents,"[https://swapi.dev/api/people/1/, https://swap...","[https://swapi.dev/api/people/5/, https://swap...",[],[],[]
films,"[https://swapi.dev/api/films/1/, https://swapi...","[https://swapi.dev/api/films/1/, https://swapi...",[https://swapi.dev/api/films/1/],[https://swapi.dev/api/films/2/],"[https://swapi.dev/api/films/2/, https://swapi..."
created,2014-12-09T13:50:49.641000Z,2014-12-10T11:35:48.479000Z,2014-12-10T11:37:19.144000Z,2014-12-10T11:39:13.934000Z,2014-12-10T11:42:22.590000Z
edited,2014-12-20T20:58:18.411000Z,2014-12-20T20:58:18.420000Z,2014-12-20T20:58:18.421000Z,2014-12-20T20:58:18.423000Z,2014-12-20T20:58:18.425000Z
url,https://swapi.dev/api/planets/1/,https://swapi.dev/api/planets/2/,https://swapi.dev/api/planets/3/,https://swapi.dev/api/planets/4/,https://swapi.dev/api/planets/5/

In [11]:
planets_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             60 non-null     object
 1   rotation_period  60 non-null     object
 2   orbital_period   60 non-null     object
 3   diameter         60 non-null     object
 4   climate          60 non-null     object
 5   gravity          60 non-null     object
 6   terrain          60 non-null     object
 7   surface_water    60 non-null     object
 8   population       60 non-null     object
 9   residents        60 non-null     object
 10  films            60 non-null     object
 11  created          60 non-null     object
 12  edited           60 non-null     object
 13  url              60 non-null     object
dtypes: object(14)
memory usage: 6.7+ KB

# STARWARS STARSHIPS

### 3. Extract the data for starships.

In [12]:
def get_starships_data():
    # Initialize the URL for the first page
    data = []
    url = 'https://swapi.dev/api/starships/'
    
    while True:
        # Send a GET request to the SWAPI
        response = requests.get(url)  
        if response.status_code == 200:
            json_data = response.json()
            results = json_data['results']
            data.extend(results)
            url = json_data['next']  

            if url is None:
                break
        else:
            print(f"Error: {response.status_code}")
            break
    # Create a DataFrame using the collected data
    df = pd.DataFrame(data)  
    return df

In [13]:
starships_df = get_starships_data()

In [14]:
starships_df.shape

(36, 18)

In [15]:
starships_df.head().T

,0,1,2,3,4
name,CR90 corvette,Star Destroyer,Sentinel-class landing craft,Death Star,Millennium Falcon
model,CR90 corvette,Imperial I-class Star Destroyer,Sentinel-class landing craft,DS-1 Orbital Battle Station,YT-1300 light freighter
manufacturer,Corellian Engineering Corporation,Kuat Drive Yards,"Sienar Fleet Systems, Cyngus Spaceworks","Imperial Department of Military Research, Sien...",Corellian Engineering Corporation
cost_in_credits,3500000,150000000,240000,1000000000000,100000
length,150,"1,600",38,120000,34.37
max_atmosphering_speed,950,975,1000,n/a,1050
crew,30-165,"47,060",5,"342,953",4
passengers,600,n/a,75,"843,342",6
cargo_capacity,3000000,36000000,180000,1000000000000,100000
consumables,1 year,2 years,1 month,3 years,2 months
hyperdrive_rating,2.0,2.0,1.0,4.0,0.5
MGLT,60,60,70,10,75
starship_class,corvette,Star Destroyer,landing craft,Deep Space Mobile Battlestation,Light freighter
pilots,[],[],[],[],"[https://swapi.dev/api/people/13/, https://swa..."
films,"[https://swapi.dev/api/films/1/, https://swapi...","[https://swapi.dev/api/films/1/, https://swapi...",[https://swapi.dev/api/films/1/],[https://swapi.dev/api/films/1/],"[https://swapi.dev/api/films/1/, https://swapi..."
created,2014-12-10T14:20:33.369000Z,2014-12-10T15:08:19.848000Z,2014-12-10T15:48:00.586000Z,2014-12-10T16:36:50.509000Z,2014-12-10T16:59:45.094000Z
edited,2014-12-20T21:23:49.867000Z,2014-12-20T21:23:49.870000Z,2014-12-20T21:23:49.873000Z,2014-12-20T21:26:24.783000Z,2014-12-20T21:23:49.880000Z
url,https://swapi.dev/api/starships/2/,https://swapi.dev/api/starships/3/,https://swapi.dev/api/starships/5/,https://swapi.dev/api/starships/9/,https://swapi.dev/api/starships/10/

In [16]:
starships_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   name                    36 non-null     object
 1   model                   36 non-null     object
 2   manufacturer            36 non-null     object
 3   cost_in_credits         36 non-null     object
 4   length                  36 non-null     object
 5   max_atmosphering_speed  36 non-null     object
 6   crew                    36 non-null     object
 7   passengers              36 non-null     object
 8   cargo_capacity          36 non-null     object
 9   consumables             36 non-null     object
 10  hyperdrive_rating       36 non-null     object
 11  MGLT                    36 non-null     object
 12  starship_class          36 non-null     object
 13  pilots                  36 non-null     object
 14  films                   36 non-null     object
 15  created                 36 non-null     object
 16  edited                  36 non-null     object
 17  url                     36 non-null     object
dtypes: object(18)
memory usage: 5.2+ KB

First interation of code. Condensed the lines to one function used above

In [17]:
# # first interation of code.. works but too many steps see starwars people. It streamlines the function. 
# def get_swplanets_data(url):
#     data = []
#     while True:
#         response = requests.get('https://swapi.dev/api/starships/')
#         if response.status_code == 200:
#             json_data = response.json()
#             results = json_data['results']
#             data.extend(results)
#             url = json_data['next']
#             if url is None:
#                 break
#         else:
#             print(f"Error: {response.status_code}")
#             break
#     return pd.DataFrame(data)

In [18]:
# url='https://swapi.dev/api/planets/'

In [22]:
# planets_df=get_swapi_data(url)

In [23]:
# def get_starships_data(url):
#     data = []
#     while True:
#         response = requests.get(url)
#         if response.status_code == 200:
#             json_data = response.json()
#             results = json_data['results']
#             data.extend(results)
#             url = json_data['next']
#             if url is None:
#                 break
#         else:
#             print(f"Error: {response.status_code}")
#             break
#     return pd.DataFrame(data)

In [24]:
# url='https://swapi.dev/api/starships/'

In [25]:
# starships_df=get_swapi_data(url)

### 4. Save the data in your files to local csv files so that it will be faster to access in the future.

### 5. Combine the data from your three separate dataframes into one large dataframe.

In [26]:
frames = [people_df, planets_df, starships_df]

In [27]:
 #this creates a new dataframe using the above variable and combining both dataframes
starwars_df = pd.concat(frames)

In [28]:
def get_starwars_data(starwars_df):
    '''This function creates a csv for concat wine csv'''
    # Assuming you have a function 'get_starwars_data()' that retrieves the starwars data and returns a DataFrame
    df_starwars = starwars_df

    # Save the DataFrame to a CSV file
    df_starwars.to_csv("starwars.csv", index=False)  # Specify 'index=False' to exclude the index column in the CSV

    filename = 'wine.csv'
    if os.path.isfile(filename):
        return pd.read_csv(filename)

In [29]:
get_starwars_data(starwars_df)

In [30]:
starwars_df.shape

(178, 38)

In [31]:
starwars_df.head().T

,0,1,2,3,4
name,Luke Skywalker,C-3PO,R2-D2,Darth Vader,Leia Organa
height,172,167,96,202,150
mass,77,75,32,136,49
hair_color,blond,n/a,n/a,none,brown
skin_color,fair,gold,"white, blue",white,light
eye_color,blue,yellow,red,yellow,brown
birth_year,19BBY,112BBY,33BBY,41.9BBY,19BBY
gender,male,n/a,n/a,male,female
homeworld,https://swapi.dev/api/planets/1/,https://swapi.dev/api/planets/1/,https://swapi.dev/api/planets/8/,https://swapi.dev/api/planets/1/,https://swapi.dev/api/planets/2/
films,"[https://swapi.dev/api/films/1/, https://swapi...","[https://swapi.dev/api/films/1/, https://swapi...","[https://swapi.dev/api/films/1/, https://swapi...","[https://swapi.dev/api/films/1/, https://swapi...","[https://swapi.dev/api/films/1/, https://swapi..."
species,[],[https://swapi.dev/api/species/2/],[https://swapi.dev/api/species/2/],[],[]
vehicles,"[https://swapi.dev/api/vehicles/14/, https://s...",[],[],[],[https://swapi.dev/api/vehicles/30/]
starships,"[https://swapi.dev/api/starships/12/, https://...",[],[],[https://swapi.dev/api/starships/13/],[]
created,2014-12-09T13:50:51.644000Z,2014-12-10T15:10:51.357000Z,2014-12-10T15:11:50.376000Z,2014-12-10T15:18:20.704000Z,2014-12-10T15:20:09.791000Z
edited,2014-12-20T21:17:56.891000Z,2014-12-20T21:17:50.309000Z,2014-12-20T21:17:50.311000Z,2014-12-20T21:17:50.313000Z,2014-12-20T21:17:50.315000Z
url,https://swapi.dev/api/people/1/,https://swapi.dev/api/people/2/,https://swapi.dev/api/people/3/,https://swapi.dev/api/people/4/,https://swapi.dev/api/people/5/
rotation_period,NaN,NaN,NaN,NaN,NaN
orbital_period,NaN,NaN,NaN,NaN,NaN
diameter,NaN,NaN,NaN,NaN,NaN
climate,NaN,NaN,NaN,NaN,NaN
gravity,NaN,NaN,NaN,NaN,NaN
terrain,NaN,NaN,NaN,NaN,NaN
surface_water,NaN,NaN,NaN,NaN,NaN
population,NaN,NaN,NaN,NaN,NaN
residents,NaN,NaN,NaN,NaN,NaN
model,NaN,NaN,NaN,NaN,NaN
manufacturer,NaN,NaN,NaN,NaN,NaN
cost_in_credits,NaN,NaN,NaN,NaN,NaN
length,NaN,NaN,NaN,NaN,NaN
max_atmosphering_speed,NaN,NaN,NaN,NaN,NaN
crew,NaN,NaN,NaN,NaN,NaN
passengers,NaN,NaN,NaN,NaN,NaN
cargo_capacity,NaN,NaN,NaN,NaN,NaN
consumables,NaN,NaN,NaN,NaN,NaN
hyperdrive_rating,NaN,NaN,NaN,NaN,NaN
MGLT,NaN,NaN,NaN,NaN,NaN
starship_class,NaN,NaN,NaN,NaN,NaN
pilots,NaN,NaN,NaN,NaN,NaN

In [32]:
starwars_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 178 entries, 0 to 35
Data columns (total 38 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   name                    178 non-null    object
 1   height                  82 non-null     object
 2   mass                    82 non-null     object
 3   hair_color              82 non-null     object
 4   skin_color              82 non-null     object
 5   eye_color               82 non-null     object
 6   birth_year              82 non-null     object
 7   gender                  82 non-null     object
 8   homeworld               82 non-null     object
 9   films                   178 non-null    object
 10  species                 82 non-null     object
 11  vehicles                82 non-null     object
 12  starships               82 non-null     object
 13  created                 178 non-null    object
 14  edited                  178 non-null    object
 15  url                     178 non-null    object
 16  rotation_period         60 non-null     object
 17  orbital_period          60 non-null     object
 18  diameter                60 non-null     object
 19  climate                 60 non-null     object
 20  gravity                 60 non-null     object
 21  terrain                 60 non-null     object
 22  surface_water           60 non-null     object
 23  population              60 non-null     object
 24  residents               60 non-null     object
 25  model                   36 non-null     object
 26  manufacturer            36 non-null     object
 27  cost_in_credits         36 non-null     object
 28  length                  36 non-null     object
 29  max_atmosphering_speed  36 non-null     object
 30  crew                    36 non-null     object
 31  passengers              36 non-null     object
 32  cargo_capacity          36 non-null     object
 33  consumables             36 non-null     object
 34  hyperdrive_rating       36 non-null     object
 35  MGLT                    36 non-null     object
 36  starship_class          36 non-null     object
 37  pilots                  36 non-null     object
dtypes: object(38)
memory usage: 54.2+ KB

### 6. Acquire the Open Power Systems Data for Germany, which has been rapidly expanding its renewable energy production in recent years. The data set includes country-wide totals of electricity consumption, wind power production, and solar power production for 2006-2017. You can get the data here: https://raw.githubusercontent.com/jenfly/opsd/master/opsd_germany_daily.csv

In [34]:
# Miatta Sinayoko came up with this
def get_power_data():
    '''
    This function acquires the Open Power Systems Data for Germany.
    It first checks if the data file exists locally and reads it if available.
    If the file does exist, it will download the data and save it as a CSV file.
    Returns a pandas DataFrame with all columns.
    '''
    filename = 'opsd_germany_daily.csv'

    # Verify if file exists
    if os.path.isfile(filename):
        return pd.read_csv(filename)
    # Download data if file doesn't exist
    else:
        url = "https://raw.githubusercontent.com/jenfly/opsd/master/opsd_germany_daily.csv"
        try:
            response = requests.get(url)
            response.raise_for_status()  # Check for any download errors
            data = response.text
            df = pd.read_csv(StringIO(data))
            df.to_csv(filename, index=False)
            print("Data acquired and saved successfully.")
            return df
        except Exception as e:
            print("Error acquiring data:", e)
            return None

# Example usage:
if __name__ == "__main__":
    power_data_df = get_power_data()
    if power_data_df is not None:
        print(power_data_df.head())

Error acquiring data: name 'StringIO' is not defined

### 7. Make sure all the work that you have done above is reproducible. That is, you should put the code above into separate functions in the acquire.py file and be able to re-run the functions and get the same data.

# CODEUP CURRICULUM WAY

In [ ]:
# # https://aphorisms.glitch.me returns a random quotation
# response = requests.get('http://aphorisms.glitch.me/')
# response

In [ ]:
# url = 'https://swapi.dev/api/planets/'
# response = requests.get('https://swapi.dev/')
# print(response.text)

In [ ]:
# #use Json for data structure 
# root_url = 'https://swapi.dev/api/'
# response = requests.get(root_url)
# print(response)
# response.json()

In [ ]:
# # looking at people dictionary specfically 
# response = requests.get('https://swapi.dev/api/planets/')
# data = response.json()
# data.keys()

In [ ]:
# number_of_planets = data['count']
# next_page = data['next']
# previous_page = data['previous']

# print(f'number_of_planets: {number_of_planets}')
# print(f'next_page: {next_page}')
# print(f'previous_page: {previous_page}')

In [ ]:
# data['results'][:60]

In [ ]:
# import math

# number_of_results = len(data['results'])
# max_page = math.ceil(number_of_planets / number_of_results)

# print(f'number_of_results: {number_of_results}')
# print(f'max_page: {max_page}')

In [ ]:
# import pandas as pd

# planets_df2 = pd.DataFrame(data['results'])
# planets_df2.head()

In [ ]:
# planets_df2.shape

In [ ]:
# response = requests.get(data['next'])
# data = response.json()

# number_of_planets = data['count']
# next_page = data['next']
# previous_page = data['previous']
# number_of_results = len(data['results'])
# max_page = math.ceil(number_of_planets / number_of_results)

# print(f'number_of_planets: {number_of_planets}')
# print(f'next_page: {next_page}')
# print(f'previous_page: {previous_page}')
# print(f'number_of_results: {number_of_results}')
# print(f'max_page: {max_page}')

# planets_df2 = pd.concat([planets_df2, pd.DataFrame(data['results'])]).reset_index()

In [ ]:
# planets_df2.shape

In [ ]:
# response = requests.get(data['next'])
# data = response.json()

# number_of_planets = data['count']
# next_page = data['next']
# previous_page = data['previous']
# number_of_results = len(data['results'])
# max_page = math.ceil(number_of_planets / number_of_results)

# print(f'number_of_planets: {number_of_planets}')
# print(f'next_page: {next_page}')
# print(f'previous_page: {previous_page}')
# print(f'number_of_results: {number_of_results}')
# print(f'max_page: {max_page}')

# planets_df2 = pd.concat([planets_df2, pd.DataFrame(data['results'])]).reset_index()